# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-31 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20171231_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
